{
 "title": "backend",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (rate(api_response_code[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P50 / P95 / P99 латентность",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 6, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum by(endpoint, le) (\n    rate(api_response_time_bucket{\n      endpoint=~\"/api/v1/.*\"\n    }[5m])\n  )\n)",
     "legendFormat": "{{endpoint}} {{status}}"
    }
   ]
  },
  {
   "title": "Overall RPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_incoming_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(api_incoming_requests{endpoint=~\"/api/v1/auth/register|/api/v1/auth/login|/api/v1/auth/logout|/api/v1/auth/me|/api/v1/auth/recovery|/api/v1/auth/settings|/api/v1/auth/verify/link|/api/v1/auth/verify/code/send|/api/v1/auth/verify/code/submit\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 10, "y": 13 },
   "targets": [
    {
     "expr": "rate(api_response_time_sum{endpoint=~\"/api/v1/.*\"}[5m])\n/\nrate(api_response_time_count{endpoint=~\"/api/v1/.*\"}[5m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}