replicaCount: 4

image:
  tag: "1.2.3"

env:
  APP_ENV: "production"

kratos:
  acceptInvalidCerts: "false"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
