name: Build Docker Images (backend)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "backend/rust_kratos/**"

jobs:
  trigger-build:
    uses: vwency/workflow/.github/workflows/buildx.yaml@main
    with:
      image-name: ${{ github.repository }}/rust-kratos
      context: "./backend/rust_kratos"
      dockerfile: "./backend/rust_kratos/Dockerfile"
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: trigger-build
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying application"

  trigger-cleanup:
    needs: [trigger-build]
    uses: vwency/workflow/.github/workflows/clean-registry.yaml@main
    with:
      owner: ${{ github.repository_owner }}
      repository: engineer-challenge
      package: engineer-challenge/rust-kratos
      keep_n_tagged: 2
      dry_run: false
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
