name: Build Docker Images (backend)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "infrastructure/helm/backend-chart/**"

jobs:
  trigger-helm-push:
    uses: vwency/workflow/.github/workflows/helm-push-ghcr.yaml@main
    with:
      chart-path: "./infrastructure/helm/backend-chart"
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
